from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import parse_qs, urlparse

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUTS_DIR = REPO_ROOT / "outputs"
DOCS_DIR = OUTPUTS_DIR / "docs"
REPORTS_DIR = OUTPUTS_DIR / "reports"
PROMPTS_DIR = REPO_ROOT / "prompts"
CACHE_DIR = REPO_ROOT / "cache"
OUTPUTS_INDEX = OUTPUTS_DIR / "INDEX.md"

_SLUG_STOPWORDS = {
    "a", "an", "the", "of", "and", "or", "for", "to", "in", "on", "at", "with",
    "watch", "live", "stream", "video", "full", "part", "vs", "ft", "feat", "by",
}


def extract_video_id(url: str) -> str:
    """Return the 11-character YouTube video id from any common URL form."""
    u = urlparse(url)
    host = (u.hostname or "").lower()

    if host in {"youtu.be"}:
        vid = u.path.lstrip("/").split("/")[0]
    elif host.endswith("youtube.com"):
        if u.path == "/watch":
            vid = parse_qs(u.query).get("v", [""])[0]
        else:
            # /live/<id>, /shorts/<id>, /embed/<id>, /v/<id>
            parts = [p for p in u.path.split("/") if p]
            vid = parts[-1] if parts else ""
    else:
        vid = url

    vid = vid.split("&")[0].split("?")[0]
    if not re.fullmatch(r"[A-Za-z0-9_-]{11}", vid):
        raise ValueError(f"Could not extract a YouTube video id from: {url!r}")
    return vid


def format_timestamp(seconds: float) -> str:
    """Seconds -> [hh:mm:ss] or [mm:ss] when under an hour."""
    s = int(round(seconds))
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    if h:
        return f"{h:02d}:{m:02d}:{sec:02d}"
    return f"{m:02d}:{sec:02d}"


def ensure_dirs() -> None:
    for d in (DOCS_DIR, REPORTS_DIR, CACHE_DIR):
        d.mkdir(parents=True, exist_ok=True)


def read_prompt(name: str) -> str:
    path = PROMPTS_DIR / name
    return path.read_text(encoding="utf-8")


def slugify_title(title: str, max_words: int = 5) -> str:
    """Produce a kebab-case slug from a YouTube title.

    Splits on non-alphanumerics, lowercases, collapses consecutive
    single-letter tokens (so "I/O" becomes "io"), strips common filler
    words, caps to ``max_words``, and always preserves a 4-digit year
    if present.
    """
    words = re.findall(r"[A-Za-z0-9]+", title.lower())
    if not words:
        return "video"

    collapsed: list[str] = []
    buf: list[str] = []
    for w in words:
        if len(w) == 1 and w.isalpha():
            buf.append(w)
        else:
            if buf:
                collapsed.append("".join(buf))
                buf = []
            collapsed.append(w)
    if buf:
        collapsed.append("".join(buf))

    year: str | None = None
    rest: list[str] = []
    for w in collapsed:
        if year is None and w.isdigit() and len(w) == 4 and 1900 <= int(w) <= 2099:
            year = w
        else:
            rest.append(w)

    filtered = [w for w in rest if w not in _SLUG_STOPWORDS]
    if not filtered:
        filtered = rest

    budget = max_words - (1 if year else 0)
    chosen = filtered[: max(budget, 1)]
    if year:
        chosen.append(year)

    return "-".join(chosen) or "video"


_INDEX_HEADER = """# Outputs index

This file maps each output slug to the source YouTube video so the filenames
in `outputs/docs/` and `outputs/reports/` are easy to recognize at a glance.

The `<id>` column is the unique YouTube video id — keep it for any script or
skill that expects the id form. The slug is auto-generated by
`ytshow.utils.slugify_title` from the video title.

| Slug | Video title | Channel | Uploaded | YouTube id | URL |
|---|---|---|---|---|---|
"""

_INDEX_FOOTER = """\n## File naming

Per video, 14 files land in `outputs/`:

```
outputs/docs/<slug>.minimal.md
outputs/docs/<slug>.rich.md

outputs/reports/<slug>.minimal.{md,pdf,docx}
outputs/reports/<slug>.rich.{md,pdf,docx}
outputs/reports/<slug>.minimal.ko.{md,pdf,docx}
outputs/reports/<slug>.rich.ko.{md,pdf,docx}
```

`<slug>` is a kebab-case abbreviation of the video title (3–5 words plus a
4-digit year when present), produced by `slugify_title`.
"""


_ESCAPED_PIPE = "\x00ESCAPED_PIPE\x00"


def _split_table_row(line: str) -> list[str]:
    """Split a Markdown table row on `|`, honoring `\\|` escapes inside cells."""
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    body = body.replace(r"\|", _ESCAPED_PIPE)
    cells = [c.replace(_ESCAPED_PIPE, "|").strip().strip("`") for c in body.split("|")]
    return cells


def _parse_outputs_index(text: str) -> list[dict[str, str]]:
    """Return the table rows in outputs/INDEX.md as a list of dicts."""
    rows: list[dict[str, str]] = []
    in_table = False
    header: list[str] = []
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith("|"):
            cells = _split_table_row(line)
            if not header:
                header = [c.lower().replace(" ", "_") for c in cells]
                in_table = True
                continue
            if set(cells) <= {"", "-", "---"}:
                continue  # divider
            if in_table and len(cells) == len(header):
                rows.append(dict(zip(header, cells)))
        elif in_table and line.startswith("#"):
            break
    return rows


def update_outputs_index(
    slug: str,
    title: str,
    channel: str,
    upload_date: str,
    video_id: str,
    url: str,
    index_path: Path = OUTPUTS_INDEX,
) -> None:
    """Insert or update a row in outputs/INDEX.md for this video.

    Idempotent: an existing row with the same slug is replaced; otherwise the
    row is appended. Rows are sorted by slug. Other rows are preserved.
    """
    index_path.parent.mkdir(parents=True, exist_ok=True)
    existing: list[dict[str, str]] = []
    if index_path.exists():
        existing = _parse_outputs_index(index_path.read_text(encoding="utf-8"))

    upload_fmt = upload_date
    if upload_date and len(upload_date) == 8 and upload_date.isdigit():
        upload_fmt = f"{upload_date[0:4]}-{upload_date[4:6]}-{upload_date[6:8]}"

    new_row = {
        "slug": slug,
        "video_title": title,
        "channel": channel,
        "uploaded": upload_fmt or "",
        "youtube_id": video_id,
        "url": url,
    }
    by_slug = {r.get("slug", ""): r for r in existing}
    by_slug[slug] = new_row
    rows_sorted = sorted(by_slug.values(), key=lambda r: r.get("slug", ""))

    def _cell(value: str) -> str:
        # Escape `|` inside cell values so the Markdown table stays well-formed.
        return (value or "").replace("|", "\\|")

    body = _INDEX_HEADER
    for r in rows_sorted:
        body += "| `{slug}` | {title} | {channel} | {uploaded} | `{vid}` | {url} |\n".format(
            slug=_cell(r.get("slug", "")),
            title=_cell(r.get("video_title", "")),
            channel=_cell(r.get("channel", "")),
            uploaded=_cell(r.get("uploaded", "")),
            vid=_cell(r.get("youtube_id", "")),
            url=_cell(r.get("url", "")),
        )
    body += _INDEX_FOOTER
    index_path.write_text(body, encoding="utf-8")


def resolve_slug_from_id(video_id: str, cache_dir: Path = CACHE_DIR) -> str | None:
    """Look up the slug for a given video id.

    Prefers a cached bundle (cache/<id>.bundle.json) for the freshest title,
    then falls back to outputs/INDEX.md.
    """
    bundle = cache_dir / f"{video_id}.bundle.json"
    if bundle.exists():
        try:
            data = json.loads(bundle.read_text(encoding="utf-8"))
            title = data.get("metadata", {}).get("title")
            if title:
                return slugify_title(title)
        except (OSError, ValueError):
            pass
    if OUTPUTS_INDEX.exists():
        for row in _parse_outputs_index(OUTPUTS_INDEX.read_text(encoding="utf-8")):
            if row.get("youtube_id") == video_id:
                return row.get("slug") or None
    return None
